#pragma once

#include <array>
#include <cstdint>

namespace nvic{

  /**
   * @brief NVIC (Nested Vectored Interrupt Controller) register map.
   *
   * Memory-mapped representation of the NVIC peripheral registers.
   * Cast a pointer to this struct at the NVIC base address (0xE000E100)
   * to access the hardware registers directly.
   */
  struct NVIC_REGS{
    
    volatile std::uint32_t NVIC_ISER0;                   // Interrupt Set-Enable Register 0  (IRQs 0–31)
    volatile std::uint32_t NVIC_ISER1;                   // Interrupt Set-Enable Register 1  (IRQs 32–63)
    volatile std::uint32_t NVIC_ISER2;                   // Interrupt Set-Enable Register 2  (IRQs 64–95)
    volatile std::uint32_t NVIC_ISER3;                   // Interrupt Set-Enable Register 3  (IRQs 96–127)
    volatile std::uint32_t NVIC_ISER4;                   // Interrupt Set-Enable Register 4  (IRQs 128–159)
    volatile std::uint32_t NVIC_ISER5;                   // Interrupt Set-Enable Register 5  (IRQs 160–191)
    volatile std::uint32_t NVIC_ISER6;                   // Interrupt Set-Enable Register 6  (IRQs 192–223)
    volatile std::uint32_t NVIC_ISER7;                   // Interrupt Set-Enable Register 7  (IRQs 224–255)
    volatile std::array<std::uint32_t, 24> UNUSED_MEM_1; // Reserved (0xE000E120–0xE000E17F)
    volatile std::uint32_t NVIC_ICER0;                   // Interrupt Clear-Enable Register 0  (IRQs 0–31)
    volatile std::uint32_t NVIC_ICER1;                   // Interrupt Clear-Enable Register 1  (IRQs 32–63)
    volatile std::uint32_t NVIC_ICER2;                   // Interrupt Clear-Enable Register 2  (IRQs 64–95)
    volatile std::uint32_t NVIC_ICER3;                   // Interrupt Clear-Enable Register 3  (IRQs 96–127)
    volatile std::uint32_t NVIC_ICER4;                   // Interrupt Clear-Enable Register 4  (IRQs 128–159)
    volatile std::uint32_t NVIC_ICER5;                   // Interrupt Clear-Enable Register 5  (IRQs 160–191)
    volatile std::uint32_t NVIC_ICER6;                   // Interrupt Clear-Enable Register 6  (IRQs 192–223)
    volatile std::uint32_t NVIC_ICER7;                   // Interrupt Clear-Enable Register 7  (IRQs 224–255)
    volatile std::array<std::uint32_t, 24> UNUSED_MEM_2; // Reserved (0xE000E1A0–0xE000E1FF)
    volatile std::uint32_t NVIC_ISPR0;                   // Interrupt Set-Pending Register 0  (IRQs 0–31)
    volatile std::uint32_t NVIC_ISPR1;                   // Interrupt Set-Pending Register 1  (IRQs 32–63)
    volatile std::uint32_t NVIC_ISPR2;                   // Interrupt Set-Pending Register 2  (IRQs 64–95)
    volatile std::uint32_t NVIC_ISPR3;                   // Interrupt Set-Pending Register 3  (IRQs 96–127)
    volatile std::uint32_t NVIC_ISPR4;                   // Interrupt Set-Pending Register 4  (IRQs 128–159)
    volatile std::uint32_t NVIC_ISPR5;                   // Interrupt Set-Pending Register 5  (IRQs 160–191)
    volatile std::uint32_t NVIC_ISPR6;                   // Interrupt Set-Pending Register 6  (IRQs 192–223)
    volatile std::uint32_t NVIC_ISPR7;                   // Interrupt Set-Pending Register 7  (IRQs 224–255)
    volatile std::array<std::uint32_t, 24> UNUSED_MEM_3; // Reserved (0xE000E220–0xE000E27F)
    volatile std::uint32_t NVIC_ICPR0;                   // Interrupt Clear-Pending Register 0  (IRQs 0–31)
    volatile std::uint32_t NVIC_ICPR1;                   // Interrupt Clear-Pending Register 1  (IRQs 32–63)
    volatile std::uint32_t NVIC_ICPR2;                   // Interrupt Clear-Pending Register 2  (IRQs 64–95)
    volatile std::uint32_t NVIC_ICPR3;                   // Interrupt Clear-Pending Register 3  (IRQs 96–127)
    volatile std::uint32_t NVIC_ICPR4;                   // Interrupt Clear-Pending Register 4  (IRQs 128–159)
    volatile std::uint32_t NVIC_ICPR5;                   // Interrupt Clear-Pending Register 5  (IRQs 160–191)
    volatile std::uint32_t NVIC_ICPR6;                   // Interrupt Clear-Pending Register 6  (IRQs 192–223)
    volatile std::uint32_t NVIC_ICPR7;                   // Interrupt Clear-Pending Register 7  (IRQs 224–255)
    volatile std::array<std::uint32_t, 24> UNUSED_MEM_4; // Reserved (0xE000E2A0–0xE000E2FF)
    volatile std::uint32_t NVIC_IABR0;                   // Interrupt Active-Bit Register 0  (IRQs 0–31)
    volatile std::uint32_t NVIC_IABR1;                   // Interrupt Active-Bit Register 1  (IRQs 32–63)
    volatile std::uint32_t NVIC_IABR2;                   // Interrupt Active-Bit Register 2  (IRQs 64–95)
    volatile std::uint32_t NVIC_IABR3;                   // Interrupt Active-Bit Register 3  (IRQs 96–127)
    volatile std::uint32_t NVIC_IABR4;                   // Interrupt Active-Bit Register 4  (IRQs 128–159)
    volatile std::uint32_t NVIC_IABR5;                   // Interrupt Active-Bit Register 5  (IRQs 160–191)
    volatile std::uint32_t NVIC_IABR6;                   // Interrupt Active-Bit Register 6  (IRQs 192–223)
    volatile std::uint32_t NVIC_IABR7;                   // Interrupt Active-Bit Register 7  (IRQs 224–255)
    volatile std::array<std::uint32_t, 24> UNUSED_MEM_5; // Reserved (0xE000E320–0xE000E37F)
    volatile std::uint32_t NVIC_IPR0;                    // Interrupt Priority Register 0  (IRQs 0–3)
    volatile std::uint32_t NVIC_IPR1;                    // Interrupt Priority Register 1  (IRQs 4–7)
    volatile std::uint32_t NVIC_IPR2;                    // Interrupt Priority Register 2  (IRQs 8–11)
    volatile std::uint32_t NVIC_IPR3;                    // Interrupt Priority Register 3  (IRQs 12–15)
    volatile std::uint32_t NVIC_IPR4;                    // Interrupt Priority Register 4  (IRQs 16–19)
    volatile std::uint32_t NVIC_IPR5;                    // Interrupt Priority Register 5  (IRQs 20–23)
    volatile std::uint32_t NVIC_IPR6;                    // Interrupt Priority Register 6  (IRQs 24–27)
    volatile std::uint32_t NVIC_IPR7;                    // Interrupt Priority Register 7  (IRQs 28–31)
    volatile std::uint32_t NVIC_IPR8;                    // Interrupt Priority Register 8  (IRQs 32–35)
    volatile std::uint32_t NVIC_IPR9;                    // Interrupt Priority Register 9  (IRQs 36–39)
    volatile std::uint32_t NVIC_IPR10;                   // Interrupt Priority Register 10 (IRQs 40–43)
    volatile std::uint32_t NVIC_IPR11;                   // Interrupt Priority Register 11 (IRQs 44–47)
    volatile std::uint32_t NVIC_IPR12;                   // Interrupt Priority Register 12 (IRQs 48–51)
    volatile std::uint32_t NVIC_IPR13;                   // Interrupt Priority Register 13 (IRQs 52–55)
    volatile std::uint32_t NVIC_IPR14;                   // Interrupt Priority Register 14 (IRQs 56–59)
    volatile std::uint32_t NVIC_IPR15;                   // Interrupt Priority Register 15 (IRQs 60–63)
    volatile std::uint32_t NVIC_IPR16;                   // Interrupt Priority Register 16 (IRQs 64–67)
    volatile std::uint32_t NVIC_IPR17;                   // Interrupt Priority Register 17 (IRQs 68–71)
    volatile std::uint32_t NVIC_IPR18;                   // Interrupt Priority Register 18 (IRQs 72–75)
    volatile std::uint32_t NVIC_IPR19;                   // Interrupt Priority Register 19 (IRQs 76–79)
    volatile std::uint32_t NVIC_IPR20;                   // Interrupt Priority Register 20 (IRQs 80–83)
    volatile std::uint32_t NVIC_IPR21;                   // Interrupt Priority Register 21 (IRQs 84–87)
    volatile std::uint32_t NVIC_IPR22;                   // Interrupt Priority Register 22 (IRQs 88–91)
    volatile std::uint32_t NVIC_IPR23;                   // Interrupt Priority Register 23 (IRQs 92–95)
    volatile std::uint32_t NVIC_IPR24;                   // Interrupt Priority Register 24 (IRQs 96–99)
    volatile std::uint32_t NVIC_IPR25;                   // Interrupt Priority Register 25 (IRQs 100–103)
    volatile std::uint32_t NVIC_IPR26;                   // Interrupt Priority Register 26 (IRQs 104–107)
    volatile std::uint32_t NVIC_IPR27;                   // Interrupt Priority Register 27 (IRQs 108–111)
    volatile std::uint32_t NVIC_IPR28;                   // Interrupt Priority Register 28 (IRQs 112–115)
    volatile std::uint32_t NVIC_IPR29;                   // Interrupt Priority Register 29 (IRQs 116–119)
    volatile std::uint32_t NVIC_IPR30;                   // Interrupt Priority Register 30 (IRQs 120–123)
    volatile std::uint32_t NVIC_IPR31;                   // Interrupt Priority Register 31 (IRQs 124–127)
    volatile std::uint32_t NVIC_IPR32;                   // Interrupt Priority Register 32 (IRQs 128–131)
    volatile std::uint32_t NVIC_IPR33;                   // Interrupt Priority Register 33 (IRQs 132–135)
    volatile std::uint32_t NVIC_IPR34;                   // Interrupt Priority Register 34 (IRQs 136–139)
    volatile std::uint32_t NVIC_IPR35;                   // Interrupt Priority Register 35 (IRQs 140–143)
    volatile std::uint32_t NVIC_IPR36;                   // Interrupt Priority Register 36 (IRQs 144–147)
    volatile std::uint32_t NVIC_IPR37;                   // Interrupt Priority Register 37 (IRQs 148–151)
    volatile std::uint32_t NVIC_IPR38;                   // Interrupt Priority Register 38 (IRQs 152–155)
    volatile std::uint32_t NVIC_IPR39;                   // Interrupt Priority Register 39 (IRQs 156–159)
    volatile std::uint32_t NVIC_IPR40;                   // Interrupt Priority Register 40 (IRQs 160–163)
    volatile std::uint32_t NVIC_IPR41;                   // Interrupt Priority Register 41 (IRQs 164–167)
    volatile std::uint32_t NVIC_IPR42;                   // Interrupt Priority Register 42 (IRQs 168–171)
    volatile std::uint32_t NVIC_IPR43;                   // Interrupt Priority Register 43 (IRQs 172–175)
    volatile std::uint32_t NVIC_IPR44;                   // Interrupt Priority Register 44 (IRQs 176–179)
    volatile std::uint32_t NVIC_IPR45;                   // Interrupt Priority Register 45 (IRQs 180–183)
    volatile std::uint32_t NVIC_IPR46;                   // Interrupt Priority Register 46 (IRQs 184–187)
    volatile std::uint32_t NVIC_IPR47;                   // Interrupt Priority Register 47 (IRQs 188–191)
    volatile std::uint32_t NVIC_IPR48;                   // Interrupt Priority Register 48 (IRQs 192–195)
    volatile std::uint32_t NVIC_IPR49;                   // Interrupt Priority Register 49 (IRQs 196–199)
    volatile std::uint32_t NVIC_IPR50;                   // Interrupt Priority Register 50 (IRQs 200–203)
    volatile std::uint32_t NVIC_IPR51;                   // Interrupt Priority Register 51 (IRQs 204–207)
    volatile std::uint32_t NVIC_IPR52;                   // Interrupt Priority Register 52 (IRQs 208–211)
    volatile std::uint32_t NVIC_IPR53;                   // Interrupt Priority Register 53 (IRQs 212–215)
    volatile std::uint32_t NVIC_IPR54;                   // Interrupt Priority Register 54 (IRQs 216–219)
    volatile std::uint32_t NVIC_IPR55;                   // Interrupt Priority Register 55 (IRQs 220–223)
    volatile std::uint32_t NVIC_IPR56;                   // Interrupt Priority Register 56 (IRQs 224–227)
    volatile std::uint32_t NVIC_IPR57;                   // Interrupt Priority Register 57 (IRQs 228–231)
    volatile std::uint32_t NVIC_IPR58;                   // Interrupt Priority Register 58 (IRQs 232–235)
    volatile std::uint32_t NVIC_IPR59;                   // Interrupt Priority Register 59 (IRQs 236–239)
  };

}